export const SET_POSTS = 'SET_POSTS';
export const FETCH_POSTS_FAILED = 'FETCH_POSTS_FAILED';
export const ADD_NEW_TICKET_SUCCESS = 'ADD_NEW_TICKET_SUCCESS';
export const ADD_NEW_TICKET_FAILED = 'ADD_NEW_TICKET_FAILED';

export const SUBMIT_COMMENT_SUCCESS = 'SUBMIT_COMMENT_SUCCESS';
export const SUBMIT_COMMENT_ERROR = 'SUBMIT_COMMENT_ERROR';

export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS';
export const GET_COMMENT_ERROR = 'GET_COMMENT_ERROR';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';



